server:
  shutdown: graceful
  tomcat:
    threads:
      max: 200 # 최대 워커 스레드 수 (default : 200)
      min-spare: 10 # 최소 유지 스레드 수 (default : 10)
    connection-timeout: 1m # 연결 타임아웃 (ms) (default : 60000ms = 1m)
    max-connections: 8192 # 최대 동시 연결 수 (default : 8192)
    accept-count: 100 # 대기 큐 크기 (default : 100)
    keep-alive-timeout: 60s # 60s
  max-http-request-header-size: 8KB
  port: 8080

spring:
  mvc.format.date: iso
  main:
    web-application-type: servlet
  threads.virtual.enabled: true
  application:
    name: commerce-api
  profiles:
    active: local
  config:
    import:
      - jpa.yml
      - redis.yml
      - logging.yml
      - monitoring.yml

  task:
    execution:
      pool:
        core-size: 8
        max-size: 16
        queue-capacity: 8

springdoc:
  use-fqn: true
  swagger-ui:
    path: /swagger-ui.html

resilience4j:
  circuitbreaker:
    configs:
      default:
        slow-call-rate-threshold: 50
        failure-rate-threshold: 50
        slow-call-duration-threshold: 300
        wait-duration-in-open-state: 1000 # OPEN -> HALF_OPEN 시도 전 대기시간
        max-wait-duration-in-half-open-state: 500
        permitted-number-of-calls-in-half-open-state: 1 # HALF_OPEN에서 시험 삼아 통과할 호출 수
        sliding-window-type: time_based
        sliding-window-size: 10 # time_based: 초 단위
        minimum-number-of-calls: 2 # 통계를 평가하기 전 최소 샘플 수 (n < sliding-window-size)
        event-consumer-buffer-size: 1
        register-health-indicator: true
        record-exceptions:
          - java.lang.Throwable

---

spring.config.activate.on-profile: local, test

server:
  address: localhost

pg-simulator:
  store-id: ${spring.application.name}
  api-client:
    base-url: http://localhost:8082

---

spring.config.activate.on-profile: dev

---

spring.config.activate.on-profile: qa

---

spring.config.activate.on-profile: prd

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
